//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projectmc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pharmacy
    {
        public int PharmacyId { get; set; }
        public string PharmacyName { get; set; }
        public string PharmacyAddress { get; set; }
        public string Manager { get; set; }
        public Nullable<int> DrugId { get; set; }
    
        public virtual Drug Drug { get; set; }
    }
}
